import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/Domain/context/userContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider>
        <html lang="en" className="w-screen h-screen p-0 m-0 overflow-x-hidden" data-theme="lemonade">
          <body className={inter.className}>{children}</body>
        </html>
    </UserProvider>
  );
}
